// -----------------------------------------------------------------------------------
// Mario Bros Beep
// -----------------------------------------------------------------------------------
// Kod lånad från https://hashtagakash.wordpress.com/2014/01/22/182/
// -----------------------------------------------------------------------------------

Console.WriteLine("Mario Bros!");

int pause = 125;
int pause2 = 250;

// Kontrollera hastigheten
int change = 5;
pause -= change;
pause2 -= change;

Console.Beep(659, pause);
Console.Beep(659, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(523, pause);
Console.Beep(659, pause);
Thread.Sleep(pause);
Console.Beep(784, pause);
Thread.Sleep(375);
Console.Beep(392, pause);
Thread.Sleep(375);
Console.Beep(523, pause);
Thread.Sleep(pause2);
Console.Beep(392, pause);
Thread.Sleep(pause2);
Console.Beep(330, pause);
Thread.Sleep(pause2);
Console.Beep(440, pause);
Thread.Sleep(pause);
Console.Beep(494, pause);
Thread.Sleep(pause);
Console.Beep(466, pause);
Thread.Sleep(42);
Console.Beep(440, pause);
Thread.Sleep(pause);
Console.Beep(392, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(pause);
Console.Beep(784, pause);
Thread.Sleep(pause);
Console.Beep(880, pause);
Thread.Sleep(pause);
Console.Beep(698, pause);
Console.Beep(784, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(pause);
Console.Beep(523, pause);
Thread.Sleep(pause);
Console.Beep(587, pause);
Console.Beep(494, pause);
Thread.Sleep(pause);
Console.Beep(523, pause);
Thread.Sleep(pause2);
Console.Beep(392, pause);
Thread.Sleep(pause2);
Console.Beep(330, pause);
Thread.Sleep(pause2);
Console.Beep(440, pause);
Thread.Sleep(pause);
Console.Beep(494, pause);
Thread.Sleep(pause);
Console.Beep(466, pause);
Thread.Sleep(42);
Console.Beep(440, pause);
Thread.Sleep(pause);
Console.Beep(392, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(pause);
Console.Beep(784, pause);
Thread.Sleep(pause);
Console.Beep(880, pause);
Thread.Sleep(pause);
Console.Beep(698, pause);
Console.Beep(784, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(pause);
Console.Beep(523, pause);
Thread.Sleep(pause);
Console.Beep(587, pause);
Console.Beep(494, pause);
Thread.Sleep(375);
Console.Beep(784, pause);
Console.Beep(740, pause);
Console.Beep(698, pause);
Thread.Sleep(42);
Console.Beep(622, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(415, pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Thread.Sleep(pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Console.Beep(587, pause);
Thread.Sleep(pause2);
Console.Beep(784, pause);
Console.Beep(740, pause);
Console.Beep(698, pause);
Thread.Sleep(42);
Console.Beep(622, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(698, pause);
Thread.Sleep(pause);
Console.Beep(698, pause);
Console.Beep(698, pause);
Thread.Sleep(625);
Console.Beep(784, pause);
Console.Beep(740, pause);
Console.Beep(698, pause);
Thread.Sleep(42);
Console.Beep(622, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(415, pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Thread.Sleep(pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Console.Beep(587, pause);
Thread.Sleep(pause2);
Console.Beep(622, pause);
Thread.Sleep(pause2);
Console.Beep(587, pause);
Thread.Sleep(pause2);
Console.Beep(523, pause);
Thread.Sleep(1125);
Console.Beep(784, pause);
Console.Beep(740, pause);
Console.Beep(698, pause);
Thread.Sleep(42);
Console.Beep(622, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(415, pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Thread.Sleep(pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Console.Beep(587, pause);
Thread.Sleep(pause2);
Console.Beep(784, pause);
Console.Beep(740, pause);
Console.Beep(698, pause);
Thread.Sleep(42);
Console.Beep(622, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(698, pause);
Thread.Sleep(pause);
Console.Beep(698, pause);
Console.Beep(698, pause);
Thread.Sleep(625);
Console.Beep(784, pause);
Console.Beep(740, pause);
Console.Beep(698, pause);
Thread.Sleep(42);
Console.Beep(622, pause);
Thread.Sleep(pause);
Console.Beep(659, pause);
Thread.Sleep(167);
Console.Beep(415, pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Thread.Sleep(pause);
Console.Beep(440, pause);
Console.Beep(523, pause);
Console.Beep(587, pause);
Thread.Sleep(pause2);
Console.Beep(622, pause);
Thread.Sleep(pause2);
Console.Beep(587, pause);
Thread.Sleep(pause2);
Console.Beep(523, pause);
